apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-devex-deploy
  labels:
    app: local-devex
spec:
  replicas: 2
  selector:
    matchLabels:
      app: local-devex
  template:
    metadata:
      labels:
        app: local-devex
    spec:
      containers:
      - name: app
        image: local/devex:v1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: local-devex-svc
spec:
  type: NodePort
  selector:
    app: local-devex
  ports:
  - name: local-devex-port
    protocol: TCP
    port: 8080
    targetPort: 8080