name: CI
on:
  - push
  - pull_request
  workflow_dispatch:
  schedule:
    # every day at 6am & 6pm pacific
    - cron: "0 1,13 * * *"
jobs:
  build:
    strategy:
      matrix:
          os: [ubuntu-latest, macos-10.15]
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - uses: azure/setup-kubectl@v3
      - uses: medyagh/setup-minikube@latest
      - name: Build Docker images inside minikube
        run: | 
          eval $(minikube docker-env)
          docker build -t local/devex:v1 .
      - name: Deploy to to Kubernetes 
        run: | 
          kubectl apply -f deploy/k8s.yaml 
      - name: Verify Deployment
        run: | 
          minikube service list
          minikube service local-devex-svc --url --wait=10
          curl -vvv $(minikube service local-devex-svc --url)
          curl -vvv $(minikube service local-devex-svc --url)/headers